version: "3"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  metrics-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
