global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'metrics-app'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'metrics-app:8080' ]
        labels:
          env: 'local'